adam_epsilon: 1.0e-08
cache_dir: ''
config_name: ''
data_dir: /dccstor/tuhinstor/tuhin/fullNQ
do_predict: false
do_train: true
eval_batch_size: 1
fp16: true
fp16_opt_level: O2
gradient_accumulation_steps: 1
learning_rate: 0.0003
max_grad_norm: 1.0
max_source_length: 3072
max_target_length: 512
model_name_or_path: bart-large
n_gpu: 1
n_tpu_cores: 0
num_train_epochs: 5
output_dir: /dccstor/tuhinstor/tuhin/fullNQ/bart_sum1
seed: 42
tokenizer_name: ''
train_batch_size: 1
warmup_steps: 0
weight_decay: 0.0
