adam_epsilon: 1.0e-08
cache_dir: ''
config_name: ''
data_dir: /dccstor/tuhinstor/tuhin/NQ-amr-qc
do_predict: true
do_train: true
eval_batch_size: 5
fp16: true
fp16_opt_level: O2
gradient_accumulation_steps: 1
learning_rate: 3.0e-05
max_grad_norm: 1.0
max_source_length: 1024
max_target_length: 256
model_name_or_path: bart-large
n_gpu: 1
n_tpu_cores: 0
num_train_epochs: 3
output_dir: /dccstor/tuhinstor/tuhin/NQ-amr-qc/bart_sum
seed: 42
tokenizer_name: ''
train_batch_size: 5
warmup_steps: 0
weight_decay: 0.0
